
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fanky Abdilqoyyim
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgType = new javax.swing.ButtonGroup();
        lbHead = new javax.swing.JLabel();
        lbPhoneNumber = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbThank = new javax.swing.JLabel();
        lbDot1 = new javax.swing.JLabel();
        lbDot2 = new javax.swing.JLabel();
        tfPhoneNumber = new javax.swing.JTextField();
        cbPrice = new javax.swing.JComboBox<>();
        lbLane1 = new javax.swing.JLabel();
        lbLane = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        lbDot3 = new javax.swing.JLabel();
        lbTotalPrice = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbHead.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbHead.setText("TOP-UP SELLER");

        lbPhoneNumber.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbPhoneNumber.setText("Phone Number");

        lbPrice.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbPrice.setText("Price");

        lbThank.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N

        lbDot1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbDot1.setText(":");

        lbDot2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbDot2.setText(":");

        cbPrice.setForeground(new java.awt.Color(102, 102, 102));
        cbPrice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a nominal price...", "Rp5.000", "Rp10.000", "Rp20.000", "Rp50.000", "Rp100.000" }));
        cbPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPriceActionPerformed(evt);
            }
        });

        lbLane1.setText("===============================================");

        lbLane.setText("===============================================");

        lbTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbTotal.setText("Total");

        lbDot3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbDot3.setText(":");

        lbTotalPrice.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbTotalPrice.setText("-");

        btnBuy.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPhoneNumber)
                            .addComponent(lbPrice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDot2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPrice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbDot1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPhoneNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbHead)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(lbLane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbLane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTotal)
                        .addGap(75, 75, 75)
                        .addComponent(lbDot3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnBuy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHead)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPhoneNumber)
                    .addComponent(lbDot1)
                    .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrice)
                    .addComponent(lbDot2)
                    .addComponent(cbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbLane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTotal)
                        .addComponent(lbDot3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuy)
                .addGap(26, 26, 26)
                .addComponent(lbThank, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPriceActionPerformed
        String price = cbPrice.getSelectedItem().toString();
        
        switch (price) {
            case "Rp5.000" -> {
                cbPrice.removeItemAt(0);
                lbTotalPrice.setText("Rp7.000");
            }
            case "Rp10.000" -> {
                cbPrice.removeItemAt(0);
                lbTotalPrice.setText("Rp12.000");
            }
            case "Rp20.000" -> {
                cbPrice.removeItemAt(0);
                lbTotalPrice.setText("Rp22.000");
            }
            case "Rp50.000" -> {
                cbPrice.removeItemAt(0);
                lbTotalPrice.setText("Rp52.000");
            }
            case "Rp100.000" -> {
                cbPrice.removeItemAt(0);
                lbTotalPrice.setText("Rp102.000");
            } default -> {
                lbTotalPrice.setText("-");
            }
        }
    }//GEN-LAST:event_cbPriceActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed

        String price = cbPrice.getSelectedItem().toString();
        
        if (tfPhoneNumber.getText().length() != 12) {
            JOptionPane.showMessageDialog(null, "The number must be 12 digits...");
        } else {
            if (!tfPhoneNumber.getText().matches("\\d+")){
                JOptionPane.showMessageDialog(null, "Nominal must be number...");
            } else {
                int result = JOptionPane.showConfirmDialog(null, "Do you want to buy this?","Confirm", JOptionPane.YES_NO_OPTION);
        
                if (result == JOptionPane.YES_OPTION){
                    lbThank.setText("Thanks for coming...");
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry, your purchase failed😢");
                }
            }
        }
    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgType;
    private javax.swing.JButton btnBuy;
    private javax.swing.JComboBox<String> cbPrice;
    private javax.swing.JLabel lbDot1;
    private javax.swing.JLabel lbDot2;
    private javax.swing.JLabel lbDot3;
    private javax.swing.JLabel lbHead;
    private javax.swing.JLabel lbLane;
    private javax.swing.JLabel lbLane1;
    private javax.swing.JLabel lbPhoneNumber;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbThank;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalPrice;
    private javax.swing.JTextField tfPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
